---
- name: Enable ZendOpcache
  lineinfile:
    dest: "{{ phpenv_root }}/versions/{{ php_version }}/etc/conf.d/10-opcache.ini"
    line: "zend_extension=opcache.so"
    create: yes

- name: Locate Pear Directories
  phpenv:
    shell: pear config-get {{ item.key }}
    phpenv_root: "{{ phpenv_root }}"
    php_version: "{{ php_version }}"
  changed_when: no
  register: current_pear_dir
  loop: "{{ pear_dirs | dict2items }}"

- name: Set Pear Directories
  phpenv:
    shell: pear config-set {{ item.item.key }} {{ pear_dirs[item.item.key] }} system
    phpenv_root: "{{ phpenv_root }}"
    php_version: "{{ php_version }}"
  when: pear_dirs[item.item.key] != item.stdout
  loop: "{{ current_pear_dir.results }}"

- name: Find Extension Directory
  phpenv:
    shell: php-config --extension-dir
    phpenv_root: "{{ phpenv_root }}"
    php_version: "{{ php_version }}"
  changed_when: no
  register: ext_dir

- name: Create PECL Temp Directories
  command: systemd-tmpfiles --create
  when:
    - ansible_connection | default('smart') != 'docker'
    - ansible_distribution_release != "trusty"
    - tempfile_result is changed or domain_tempfile_result is changed
  become: yes

- name: Update PECL Channel
  phpenv:
    shell: pecl channel-update pecl.php.net
    php_version: "{{ php_version }}"
    phpenv_root: "{{ phpenv_root }}"
  when: install_php_result is changed

- name: Install PECL Extensions
  phpenv:
    shell: yes '' | pecl install {{ item.name }}-{{ item.version }}
    creates: "{{ ext_dir.stdout }}/{{ item.name }}.so"
    phpenv_root: "{{ phpenv_root }}"
    php_version: "{{ php_version }}"
  loop: "{{ pecl_extensions | default([]) }}"

- name: Enable PECL Extensions
  lineinfile:
    dest: "{{ phpenv_root }}/versions/{{ php_version }}/etc/conf.d/{{ item.weight | default(20) }}-{{ item.name }}.ini"
    line: "extension={{ item.name }}.so"
    create: yes
  loop: "{{ pecl_extensions | default([]) }}"

# Xdebug is enabled by phpenv.sh profile script
- name: Install Xdebug
  phpenv:
    shell: pecl install xdebug-{{ xdebug_version }}
    creates: "{{ ext_dir.stdout }}/xdebug.so"
    phpenv_root: "{{ phpenv_root }}"
    php_version: "{{ php_version }}"
  when: env_name == "dev"
