---
- name: Add Suhosin APT Key
  apt_key: url=https://sektioneins.de/files/repository.asc state=present
  become: yes

- name: Add Suhosin APT Repository
  apt_repository:
    repo: 'deb [arch=amd64] http://repo.suhosin.org/ ubuntu-trusty main'
    state: present
  become: yes

- name: Install Suhosin Extension
  apt: package=php5-suhosin-extension state=present
  become: yes
  notify: Restart FPM

- name: Add php5enmod Settings to Suhosin
  lineinfile:
    dest: /etc/php5/mods-available/suhosin.ini
    line: "{{ item }}"
    insertbefore: BOF
  become: yes
  with_items:
    - "; priority=01"
    - "; configuration for php Suhosin module"

- name: Update Suhosin Configuration
  lineinfile:
    dest: /etc/php5/mods-available/suhosin.ini
    state: present
    regexp: "{{ item.regex }}"
    line: "{{ item.line }}"
  become: yes
  notify: Restart FPM
  # regex_escape could probably make these a hell of a lot cleaner, but is 2.0+ only.
  with_items:
    - { regex: '^;?suhosin\.log\.file\s?=',                        line: "suhosin.log.file = 479 ; S_ALL & ~S_SQL" }
    - { regex: '^;?suhosin\.log\.file\.name\s?=',                  line: "suhosin.log.file.name = /var/log/php/suhosin.log" }
    - { regex: '^;?suhosin\.executor\.include\.max_traversal\s?=', line: "suhosin.executor.include.max_traversal = 5" }
    - { regex: '^;?suhosin\.executor\.include\.whitelist\s?=',     line: "suhosin.executor.include.whitelist = phar" }
    - { regex: '^;?suhosin\.executor\.disable_emodifier\s?=',      line: "suhosin.executor.disable_emodifier = On" }
    - { regex: '^;?suhosin\.mail\.protect\s?=',                    line: "suhosin.mail.protect = 1" }
    - { regex: '^;?suhosin\.memory_limit\s?=',                     line: "suhosin.mail.protect = {{ suhosin_memory_limit }}" }
    - { regex: '^;?suhosin\.sql\.comment\s?=',                     line: "suhosin.sql.comment = 1" }
    - { regex: '^;?suhosin\.sql\.opencomment\s?=',                 line: "suhosin.sql.opencomment = 2" }
    - { regex: '^;?suhosin\.session\.cryptua\s?=',                 line: "suhosin.session.cryptua = On" }
    - { regex: '^;?suhosin\.cookie\.encrypt\s?=',                  line: "suhosin.cookie.encrypt = On" }

- name: Set Cookie Encryption Key
  lineinfile:
    dest: /etc/php5/mods-available/suhosin.ini
    state: present
    regexp: ^;?suhosin\.cookie\.cryptkey\s?=
    line: >
      suhosin.cookie.cryptkey = {{ lookup('password',
      storage_dir + '/' + ansible_hostname + '/suhosin-cookie-key chars=ascii_letters,digits length=64') }}
  become: yes
  notify: Restart FPM

- name: Set Session Encryption Key
  lineinfile:
    dest: /etc/php5/mods-available/suhosin.ini
    state: present
    regexp: ^;?suhosin\.session\.cryptkey\s?=
    line: >
      suhosin.session.cryptkey = {{ lookup('password',
      storage_dir + '/' + ansible_hostname + '/suhosin-session-key chars=ascii_letters,digits length=64') }}
  become: yes
  notify: Restart FPM

- name: Add Suhosin Log Path
  set_fact:
    log_files: "{{ log_files }} + [ '/var/log/php/suhosin.log' ]"

- name: Enable Suhosin Configuration
  command: php5enmod suhosin creates=/etc/php5/fpm/conf.d/01-suhosin.ini
  become: yes
  notify: Restart FPM
